services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Interface aliases
    App\Contract\Bus\CommandBusInterface: '@App\Infrastructure\Bus\SimpleCommandBus'
    App\Contract\Bus\QueryBusInterface: '@App\Infrastructure\Bus\SimpleQueryBus'
    Psr\Cache\CacheItemPoolInterface: '@App\Infrastructure\Cache\FileCacheAdapter'

    # Infrastructure
    App\Contract\Bus\Locator\HandlerLocatorInterface: '@App\Infrastructure\Bus\Locator\ConventionBasedHandlerLocator'

    App\Infrastructure\Bus\Locator\ConventionBasedHandlerLocator:
        arguments:
            $container: '@service_container'

    App\Infrastructure\Bus\SimpleCommandBus:
        arguments:
            $locator: '@App\Contract\Bus\Locator\HandlerLocatorInterface'
            $middlewares: []

    App\Infrastructure\Bus\Middleware\QueryCacheMiddleware:
        arguments: ['@App\Infrastructure\Cache\FileCacheAdapter']

    App\Infrastructure\Bus\SimpleQueryBus:
        arguments:
            $locator: '@App\Contract\Bus\Locator\HandlerLocatorInterface'
            $middlewares:
                - '@App\Infrastructure\Bus\Middleware\QueryCacheMiddleware'

    # Make handlers public so the simple bus can locate them via container
    App\Application\CommandHandler\:
        resource: '../src/Application/CommandHandler/'
        public: true

    App\Application\QueryHandler\:
        resource: '../src/Application/QueryHandler/'
        public: true
