<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_solana_contract_index' => [[], ['_controller' => 'App\\Controller\\SolanaContractController::index'], [], [['text', '/solana/contract/']], [], [], []],
    'app_solana_contract_new' => [[], ['_controller' => 'App\\Controller\\SolanaContractController::new'], [], [['text', '/solana/contract/new']], [], [], []],
    'app_solana_contract_show' => [['id'], ['_controller' => 'App\\Controller\\SolanaContractController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/solana/contract']], [], [], []],
    'app_solana_contract_validate' => [['id'], ['_controller' => 'App\\Controller\\SolanaContractController::validate'], [], [['text', '/validate'], ['variable', '/', '[^/]++', 'id', true], ['text', '/solana/contract']], [], [], []],
    'App\Controller\SolanaContractController::index' => [[], ['_controller' => 'App\\Controller\\SolanaContractController::index'], [], [['text', '/solana/contract/']], [], [], []],
    'App\Controller\SolanaContractController::new' => [[], ['_controller' => 'App\\Controller\\SolanaContractController::new'], [], [['text', '/solana/contract/new']], [], [], []],
    'App\Controller\SolanaContractController::show' => [['id'], ['_controller' => 'App\\Controller\\SolanaContractController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/solana/contract']], [], [], []],
    'App\Controller\SolanaContractController::validate' => [['id'], ['_controller' => 'App\\Controller\\SolanaContractController::validate'], [], [['text', '/validate'], ['variable', '/', '[^/]++', 'id', true], ['text', '/solana/contract']], [], [], []],
];
