<?php

namespace ContainerRP3WXzJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\SolanaContractController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\SolanaContractController::index()', 'getSolanaContractControllerindexService', true],
            'App\\Controller\\SolanaContractController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\SolanaContractController::new()', 'getSolanaContractControllernewService', true],
            'App\\Controller\\SolanaContractController::show' => ['privates', '.service_locator.lTlQX2H.App\\Controller\\SolanaContractController::show()', 'getSolanaContractControllershowService', true],
            'App\\Controller\\SolanaContractController::validate' => ['privates', '.service_locator.MWTw0ZY.App\\Controller\\SolanaContractController::validate()', 'getSolanaContractControllervalidateService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\SolanaContractController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\SolanaContractController::index()', 'getSolanaContractControllerindexService', true],
            'App\\Controller\\SolanaContractController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\SolanaContractController::new()', 'getSolanaContractControllernewService', true],
            'App\\Controller\\SolanaContractController:show' => ['privates', '.service_locator.lTlQX2H.App\\Controller\\SolanaContractController::show()', 'getSolanaContractControllershowService', true],
            'App\\Controller\\SolanaContractController:validate' => ['privates', '.service_locator.MWTw0ZY.App\\Controller\\SolanaContractController::validate()', 'getSolanaContractControllervalidateService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Controller\\SolanaContractController::index' => '?',
            'App\\Controller\\SolanaContractController::new' => '?',
            'App\\Controller\\SolanaContractController::show' => '?',
            'App\\Controller\\SolanaContractController::validate' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\SolanaContractController:index' => '?',
            'App\\Controller\\SolanaContractController:new' => '?',
            'App\\Controller\\SolanaContractController:show' => '?',
            'App\\Controller\\SolanaContractController:validate' => '?',
        ]));
    }
}
