<?php

namespace ContainerRP3WXzJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSolanaContract2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lTlQX2H.App\Entity\SolanaContract' shared service.
     *
     * @return \App\Entity\SolanaContract
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lTlQX2H": it needs an instance of "App\\Entity\\SolanaContract" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
